services:
  jellyseerr:
    image: fallenbagel/jellyseerr:latest
    container_name: jellyseerr
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - LOG_LEVEL=error
      - TZ=${TZ}
    ports:
      - 5055:5055
    volumes:
      - ${CONFIG_PATH}/configs/jellyseerr:/app/config
    restart: unless-stopped
