services:
  jellyfin:
    image: lscr.io/linuxserver/jellyfin:latest
    container_name: jellyfin
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
      - NVIDIA_VISIBLE_DEVICES=all
    ports:
      - 8096:8096
      - 8920:8920
      - 7359:7359/udp
      - 1900:1900/udp
    volumes:
      - ${MEDIA_PATH}:/media
      - ${MEDIA_PATH}/tv:/media/tv
      - ${MEDIA_PATH}/movies:/media/movies
      - ${CONFIG_PATH}/configs/jellyfin:/config
      - ${CONFIG_PATH}/jellyfin/cache:/cache
      - ${DOWNLOAD_PATH}:/media/media_downloads
    devices:
      - /dev/dri:/dev/dri
    restart: unless-stopped
